version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongo:27017/face_recognition_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./ssl:/app/ssl
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - face-recognition-net
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=face_recognition_prod
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword123
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data_prod:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - face-recognition-net
    command: mongod --auth

  redis:
    image: redis:7-alpine
    environment:
      - REDIS_PASSWORD=redispassword123
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - face-recognition-net
    command: redis-server --appendonly yes --requirepass redispassword123

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./static:/var/www/static
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - face-recognition-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    networks:
      - face-recognition-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafanapassword123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - face-recognition-net

  backup:
    image: mongo:5.0
    volumes:
      - mongo_data_prod:/data/db:ro
      - ./backups:/backup
    environment:
      - MONGO_URI=mongodb://admin:securepassword123@mongo:27017/face_recognition_prod?authSource=admin
    command: |
      sh -c '
        while true; do
          echo "Starting backup at $$(date)"
          mongodump --uri="$$MONGO_URI" --out=/backup/mongo_backup_$$(date +%Y%m%d_%H%M%S)
          find /backup -name "mongo_backup_*" -mtime +7 -exec rm -rf {} \;
          echo "Backup completed at $$(date)"
          sleep 86400
        done
      '
    networks:
      - face-recognition-net
    restart: unless-stopped

volumes:
  mongo_data_prod:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  face-recognition-net:
    driver: bridge